### ISSUE TITLE
Share schema-to-engine compilation and reject unsupported profile behavior

### ISSUE THREAD

**Issue by 2001J** [2001J/fuzzy-parser#12]
## Completion review — 2026-08-28

Independently reviewed and integrated locally. Ticket commit: `93229f15cdd1993593eef7d8e26400bf4c7f4cd5`; integration commit: `832e4f5816f506ef25c2796942eb265c3b122d22`. No commit is published; remote main remains `8f878a45d7801ab0ca0a7d10a1b8aca353c7c192`.

- Delivered shared strict execution decoding and schema compilation into a core ParsePlan. CLI and Rust callers share core execution; the CLI-owned assignment_spec is removed. Structural TargetSchema decoding, lower-level public APIs, versions, success shapes and legacy global-enum semantics remain compatible.
- Per-field canonical/alias eligibility prevents enum leakage. Unique existing header then label context resolves ownership before constraints; tied hypotheses stay unassigned with enum_field_ambiguous, without double assignment. All detected/assigned/unassigned source references and raw/unused evidence remain.
- The approved option, constraint, unknown-property and enum-definition failures are explicit and default-safe. Programmatic schemas are validated; all supported type/constraint combinations, repeated bounds, positional struct arrays, unit enum objects and existing structural/input/type-error precedence are covered. Unsupported text/person_name/datetime remain explicit.
- Coordinator independently reviewed schema compiler/decoder, CLI/error changes, docs and permanent regressions. A separate core/enum reviewer found no issues and ran 34 focused new/legacy checks. All 12 pre-change golden cases were also executed against the previous reviewed parser binary and matched exact stdout/streams/exits.
- Worker slice: all 213 native Rust tests passed independently. Combined with #5: all 232 macOS tests and 233 Linux/amd64 tests passed, no ignored tests; all names from both branches and the six original Cargo targets remain. Formatting, locked all-target Clippy with warnings denied, workspace build/release and three-library WASM compilation passed.
- Combined 11 Node guard tests, native parity (11 successes, 9 errors, 7 controls, 2,476 source resolutions, 22 cleanups) and all 14 real-container checks passed. Image `fuzzy-parser-schema-validation-review:local`, digest `sha256:0c9131bb47e49856bab64619dfac8ae4f3b14e546a8e6ed95b3af255e78aa563`.
- Integration required only a roadmap conflict resolution plus anchoring the new test fixture include to CARGO_MANIFEST_DIR per the test-layout convention. The final anchored test source was included read-only in the isolated network-disabled Linux run, alongside synthetic fixtures; production image sources were unchanged. Both native and Linux suites passed after that test-only adjustment. Combined whitespace checks and 82 local documentation links/anchors passed.

Closed for the approved shared compiler and field-scoped execution scope. This does not implement names/text, normalization/segmentation composition, table controls, resource limits, WASM/JS execution, an adapter or QualEvents adoption. Low-level unchecked plan constructors are not schema validation. #11/#13–#19 and hosted CI #23 retain their separate gates. No dependency, manifest, workflow, host, production, push or publication change occurred.

Earlier scope decisions and original acceptance criteria are retained below.

---

## Scoped execution decisions — 2026-08-28

The coordinator has independently reviewed and locally integrated #2, #4 and #15 at code baseline 51211e0 (183 passing Rust tests). #2 is closed; this ticket's prerequisite is resolved. Implementation will run in its own branch/worktree and remains open until full independent review.

- Keep raw schema models and structural deserialization compatible. Add a strict **execution** decoding path before unknown properties are discarded; use it for CLI parse and document it for JSON library callers. A typed compiler cannot recover already-discarded JSON keys. Structural schema validation alone remains distinct.
- Preserve supported-profile full output and existing failure precedence during the mechanical compiler move. Run all existing detectors; do not lose unrelated candidate/source evidence. Keep existing lower-level public APIs and one shared core implementation.
- Treat allow_unknown_fields=true as permissive preservation of unused/unassigned evidence; reject false explicitly until strict data policy exists. Reject inapplicable constraints during compilation, while preserving applicable inclusive bounds, normalized-string Unicode-scalar lengths and repeated-constraint conjunction. These are documented corrections to previously ignored or ineffective settings.
- Preserve per-field enum lexical eligibility and canonicalization, not just canonical membership. Resolve cross-field occurrence ownership only with uniquely decisive existing header/label context; otherwise keep competing hypotheses unresolved, warn, and never assign one occurrence twice. Preserve every source reference and raw fragment. Reject within-field lexical collisions; preserve multiword canonical output reached through a supported short alias. No new phrase detector. Unsupported enum-definition behavior must be explicit rather than silently advertised.
- Minimal typed safe capability failures may be added under error contract 0.1 with migration notes and exact tests: schema_option_unsupported, schema_constraint_unsupported, schema_property_unsupported, schema_enum_definition_ambiguous, and schema_enum_definition_unsupported where a definition cannot execute. Proposed unresolved-ownership warning: enum_field_ambiguous. No caller strings in default errors; raw/response/schema shapes and existing codes remain. Document exhaustive Rust-match/typed-reader impacts.
- Do not implement #13/#14/#16/#17 or a runtime/host adapter here. Capture pre-change compatibility and red regressions first. Any other success-output change, public shape change, new policy or source loss stops for coordinator review.

The original Tests and acceptance criteria below still apply; these decisions do not claim implementation or waive them. No push, main merge, publication, deployment or host work is authorized.

---

# Goal

All integration surfaces interpret a caller schema identically without duplicating the CLI's assignment_spec logic.

# Success criteria

- Move schema-to-assignment compilation into a reusable library boundary with directional dependencies; keep raw schema models in parser-schema and runtime behavior outside the CLI.
- Preserve each enum field's allowed values and aliases instead of pooling every enum definition into an unrestricted common candidate type.
- Explicitly support or reject each accepted option/constraint. In particular, allow_unknown_fields is serialized today but ignored by parse; do not silently ignore it.
- Report text/person_name/datetime capability gaps until their implementations exist; do not call schema validation proof that execution supports every field.
- Document currently supported profile options. Locale, country hints, expected-column configuration, uniqueness, and runtime limits must not be advertised as effective CLI schema features unless implemented and tested.

# Tests

Compare existing CLI fixtures before/after extraction of the compiler. Test two enum fields with disjoint values and overlapping aliases; no cross-field assignment. Test ignored/unsupported options explicitly, required/multiple fields, range/length constraints, stable errors, and a non-CLI caller using the same API.

Run the repository checks for implementation changes:

```bash
cargo fmt --check
cargo clippy --workspace --all-targets -- -D warnings
cargo test --workspace
cargo build --workspace
```

# Dependencies

#2 for the safe error boundary. #13, #14, #16, #17, and #18 reuse the resulting API.

# Constraints

Generic Fuzzy Parser work only. Use synthetic input. No QualEvents code or tracker changes, production access, database writes, messaging, deployment, package publication, or release actions. Preserve raw input and existing contracts unless this ticket explicitly documents a versioned migration.

Do not add speculative generic traits or create a crate solely for convenience. Document any dependency change; no circular dependencies.

# Output

Reusable schema compilation API, thin CLI conversion, regression tests, and accurate capability documentation.

# Stop rules

Do not mark acceptance complete from a successful exit status alone; assert semantic results and source evidence. Keep uncertain or unsupported cases explicit.

**Comment by 2001J** [comment]
## Local implementation evidence — pending independent review

Implemented #12 on `codex/fp-12-schema-compilation` from reviewed baseline `782ccd43a3deb5a5b2ffa3dc773f0c980996444a`. Changes are uncommitted and unstaged; no integration, push, publication or closure is claimed.

- Shared `parser-schema` compilation and strict execution decoding produce a private-representation core `ParsePlan`. CLI and library callers share detector/assignment internals; existing lower-level APIs and raw/schema/response shapes remain compatible.
- Per-field enum lexical ownership/canonicalization, decisive header/label context, unresolved `enum_field_ambiguous` hypotheses, explicit unsupported capabilities and the five approved safe failure codes are implemented. Structural decoding remains distinct, including accepted positional arrays/unit-type objects. Existing unsupported-type failures keep precedence over newly introduced compilation failures.
- Before production changes, baseline 183 tests passed. New tests for disjoint enum leakage, ignored `allow_unknown_fields=false`, and unknown execution properties failed, while old-profile parity and failure-precedence controls passed. Mechanical compiler extraction preserved the recorded output before semantic corrections; these regressions now pass.
- A permanent 12-case pre-change fixture locks complete contact/attendance/inventory output across TXT, stdin, CSV and XLSX. New library and CLI tests check exact sources, unused content, review/warnings, determinism, aliases/ownership, constraints and safe/detailed errors.

Verification passed: `cargo fmt --check`; locked workspace Clippy with all targets and warnings denied; locked workspace tests and build; three-library `wasm32-unknown-unknown` compilation; 11 Node guard tests; rebuilt-release native invocation parity (2,476 source-reference checks, 9 exact stderr parity cases); `git diff --check`; 79 local documentation links/anchors and the affected README schema/parse examples.

Rust discovery is unchanged at six Cargo targets: **213 passing tests = all 183 original names + 30 additions** (7 CLI, 23 schema-library). No original expectation migrations were needed; approved behavior corrections are documented and tested separately. Docker remains assigned to the coordinator and was not run here. No #13/#14/#16/#17, runtime adapter, new dependency/crate or consumer-specific behavior was added.

Issue remains open for coordinator review and integration.
